Disable junit tests to diagnose maven build issue

diff --git a/.github/workflows/maven-publish-linux.yml b/.github/workflows/maven-publish-linux.yml
--- a/.github/workflows/maven-publish-linux.yml
+++ b/.github/workflows/maven-publish-linux.yml
@@ -23,13 +23,13 @@ jobs:
         settings-path: ${{ github.workspace }} # location for the settings.xml file
 
     - name: Build with Maven
-      run: mvn install -s $GITHUB_WORKSPACE/settings.xml
+      run: mvn install -s $GITHUB_WORKSPACE/settings.xml -DskipTests
       env:
         GITHUB_TOKEN: ${{ github.token }}
 
-    # this is nasty! the publish fails as the pom already exists but we only really want to artefact published, so we try to ignore the error
+    # this is nasty! the publish fails as the pom already exists but we only really want the artefact published, so we try to ignore the error
     # this is also why the full build is performed in the previous step as we do want that to fail if there are other errors in the build
     - name: Publish to GitHub Packages Apache Maven
-      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml || echo "Ignoring non-zero result"
+      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -DskipTests || echo "Ignoring non-zero result"
       env:
         GITHUB_TOKEN: ${{ github.token }}
